---
- name: Install and Configure V2raya
  hosts: localhost
  become: true

  tasks:
    - name: Download and Install v2ray core
      ansible.builtin.shell:
        cmd: |
          wget -O /tmp/v2ray-linux-64.zip https://ghproxy.net/https://github.com/v2fly/v2ray-core/releases/download/v5.13.0/v2ray-linux-64.zip
          openssl dgst -SHA2-256 /tmp/v2ray-linux-64.zip
          sudo unzip /tmp/v2ray-linux-64.zip -d /usr/local/v2ray-core
          sudo mkdir -p /usr/local/share/v2ray/
          sudo cp /usr/local/v2ray-core/*dat /usr/local/share/v2ray/

    - name: Download and Install v2rayA
      ansible.builtin.shell:
        cmd: |
          wget -O /tmp/installer_debian_x64_2.2.4.6.deb https://ghproxy.net/https://github.com/v2rayA/v2rayA/releases/download/v2.2.4.6/installer_debian_x64_2.2.4.6.deb
          openssl dgst -SHA2-256 /tmp/installer_debian_x64_2.2.4.6.deb
          sudo apt install /tmp/installer_debian_x64_2.2.4.6.deb

    - name: Configure v2rayA bin
      ansible.builtin.lineinfile:
        path: /etc/default/v2raya
        regexp: V2RAYA_V2RAY_BIN
        line: V2RAYA_V2RAY_BIN=/usr/local/v2ray-core/v2ray

    - name: Configure v2rayA directory
      ansible.builtin.lineinfile:
        path: /etc/default/v2raya
        regexp: V2RAYA_V2RAY_CONFDIR
        line: V2RAYA_V2RAY_CONFDIR=/usr/local/v2ray-core

    - name: Configure v2rayA to start at boot time
      ansible.builtin.service:
        name: v2raya
        state: started
        enabled: true

          
